"""empty message

Revision ID: 92f78cc09a6b
Revises: 78ed94b5bb1e
Create Date: 2022-10-18 00:45:25.029636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92f78cc09a6b'
down_revision = '78ed94b5bb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.add_column('People', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'People', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'People', type_='foreignkey')
    op.drop_column('People', 'user_id')
    op.create_table('tags',
    sa.Column('User_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('People_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['People_id'], ['People.id'], name='tags_ibfk_1'),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], name='tags_ibfk_2'),
    sa.PrimaryKeyConstraint('User_id', 'People_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
