"""empty message

Revision ID: 9ba27d6d901c
Revises: 92f78cc09a6b
Create Date: 2022-10-18 00:47:02.578721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba27d6d901c'
down_revision = '92f78cc09a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Planets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Planets', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Planets', type_='foreignkey')
    op.drop_column('Planets', 'user_id')
    # ### end Alembic commands ###
